name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm deploy
      run: |
        npm install
        git config --global user.email "action@sandeshshrestha.com"
        git config --global user.name "Github Action"
        npm run deploy
      env:
        CI: true
